sudo: false
language: ruby
rvm:
  - 2.2.5
  - 2.3.3
  - ruby-head
  - jruby-9.1.5.0
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.5.0
before_install: gem install bundler -v 1.13.6
